# -*- coding: utf-8 -*-
"""Module 2 - Statistics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18418ax59aYYI_blikZ_6GwyzbU86hq74
"""

### Tính mean (trị trung bình)
import numpy as np

def compute_mean(X):
  return np.sum(X) / len(X)

X = [2, 0, 2, 2, 7, 4, -2, 5, -1, -1]

print("Mean : ", compute_mean(X))

### Tính median (phương sai)

def compute_median(X):
  size = len(X)
  X = np.sort(X)
  print(X)
  if (size % 2 == 0):
    return (1/2*(X[int(size/2)-1] \
                 + (X[int(size/2) + 1 - 1])))
  else:
    return X[int((size+1)/2)-1]

X = [1, 5, 4, 4, 9, 13]
print("Median: ", compute_median(X))

### Tính std (độ lệch chuẩn)

def compute_std(X):
  mean = compute_mean(X)
  variance = 0
  for x in X:
    variance = variance + (x - mean)**2
  variance = variance / len(X)
  return np.sqrt(variance)

X = [ 171, 176, 155, 167, 169, 182]
print(np.round(compute_std(X),2))

data = np.array([ 171, 176, 155, 167, 169, 182])

print("Mean: ", np.mean(data))
print("edian: ", np.median(data))
print("Std: ", np.std(data))
print("Variance: ", np.var(data))

### Tính Correlation

def compute_correlation_cofficient(X, Y):
  N = len(X)
  numerator = N * X.dot(Y) - np.sum(X)*np.sum(Y)
  denominator = np.sqrt(N*np.sum(np.square(X))-np.sum(X)**2) \
    * np.sqrt(N*np.sum(np.square(Y))-np.sum(Y)**2)

  return np.round(numerator / denominator,2)

X = np.asarray([-2, -5, -11, 6, 4, 15, 9])
Y = np.asarray([4, 25, 121, 36, 16, 225, 81])
print("Correlation: ", compute_correlation_cofficient(X,Y))

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

data = pd.read_csv("./advertising.csv")
data
data.info()

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
def correlation(x, y):
  x_mean = np.mean(x)
  y_mean = np.mean(y)

  numerator = np.sum((x - x_mean) * (y - y_mean))
  denominator = np.sqrt(np.sum((x - x_mean)**2) * np.sum((y - y_mean)**2))

  if denominator == 0:
    return 0  # Handle cases where the denominator is zero

  return numerator / denominator

x = data['Radio']
y = data['Newspaper']

result = correlation(x, y)
print(round(result, 2))

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

def correlation(x, y):
  x_mean = np.mean(x)
  y_mean = np.mean(y)

  numerator = np.sum((x - x_mean) * (y - y_mean))
  denominator = np.sqrt(np.sum((x - x_mean)**2) * np.sum((y - y_mean)**2))

  if denominator == 0:
    return 0  # Handle cases where the denominator is zero

  return numerator / denominator
features = ['TV', 'Radio', 'Newspaper']

for feature_1 in features:
  for feature_2 in features:
      correlation_value = correlation(data[feature_1], data[feature_2])
      print(f"{feature_1} and {feature_2}: {round(correlation_value, 2)}")

import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer

!gdown 1jh2p2DlaWsDo_vEWIcTrNh3mUuXd-cw6

vi_data_df = pd.read_csv("./vi_text_retrieval.csv")
vi_data_df
context = vi_data_df['text']
context = [doc.lower() for doc in context]
context[:5]
tfidf_vectorizer = TfidfVectorizer()
context_embedded = tfidf_vectorizer.fit_transform(context)
context_embedded.shape
context_embedded.toarray()[7][0]

vi_data_df.iloc[0]
question = vi_data_df.iloc[0]['question']
question
query_embedded = tfidf_vectorizer.transform([question.lower()])
query_embedded.shape
cosine_scores = cosine_similarity(context_embedded, query_embedded).reshape((-1,))
top_d = 5
for idx in cosine_scores.argsort()[-top_d:][::-1]:
    print("Score: ", cosine_scores[idx])
    print(vi_data_df.iloc[idx, 2])
    print("=======")

def tfidf_search(question, tfidf_vectorizer, top_d=5):
    query_embedded = tfidf_vectorizer.transform([question.lower()])
    cosine_scores = cosine_similarity(context_embedded, query_embedded).reshape((-1,))
    results = []
    for idx in cosine_scores.argsort()[-top_d:][::-1]:
        doc = {
            'id': idx,
            'cosine_score':cosine_scores[idx]
        }
        results.append(doc)
    return results

    question = vi_data_df.iloc[0]['question']
print("Question: ", question)
results = tfidf_search(question, tfidf_vectorizer)
for result in results:
    print("Id: ", result['id'])
    print("Score: ", result['cosine_score'])
    print(vi_data_df.iloc[result['id'], 2])
    print("=======")

question = vi_data_df.iloc[7]['question']
print("Question: ", question)
results = tfidf_search(question, tfidf_vectorizer)
for result in results:
    print("Id: ", result['id'])
    print("Score: ", result['cosine_score'])
    print(vi_data_df.iloc[result['id'], 2])
    print("=======")
question = vi_data_df.iloc[0]['question']
question
query_embedded = tfidf_vectorizer.transform([question.lower()])
query_embedded.shape

corr_scores = np.corrcoef(
    query_embedded.toarray()[0],
    context_embedded.toarray()
)

top_d = 5
for idx in corr_scores[0][1:].argsort()[-top_d:][::-1]:
    print("Score: ", corr_scores[0][idx])
    print(vi_data_df.iloc[idx, 2])
    print("=======")