# -*- coding: utf-8 -*-
"""Vector & Matrix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uvSddn83ThjnrZnTqVL99YPJ1JZxX0SK
"""

import numpy as np
# Tính độ dài vector
def computeVectorLength(vector):
  len_of_vector = np.linalg.norm(vector)  #hàm trong numpy

  return len_of_vector

vector = np.array([-2, 4, 9, 21])
result = computeVectorLength([vector])
print(round(result,2))

# Tích vô hướng
import numpy as np
def computeDotProduct(vector1, vector2):
  result = np.dot(vector1, vector2)

  return result

v1 = np.array([0, 1, -1, 2])
v2 = np.array([2, 5, 1, 0])
result = computeDotProduct(v1, v2)

print(round(result,2))

# Nhân vector với matrận
import numpy as np
def matrix_multi_vector(matrix, vector):
  result = np.dot(matrix, vector)
  return result

m = np.array([[-1, 1, 1], [0, -4, 9]])
v = np.array([0, 2, 1])
result = matrix_multi_vector(m, v)
print(result)

# Nhân ma trận với matrận
import numpy as np
def matrix_multi_matrix(matrix1, matrix2):
  result = np.dot(matrix1, matrix2)
  return result

m1 = np.array([[0, 1, 2], [2, -3, 1]])
m2 = np.array([[1, -3],[6, 1], [0, -1]])
result = matrix_multi_matrix(m1, m2)
print(result)

# Ma trận nghịch đảo
import numpy as np
def inverse_matrix(matrix):
  result = np.linalg.inv(matrix)
  return result

m1 = np.array([[-2, 6], [8, -4]])
result = inverse_matrix(m1)
print(result)

# Eigenvector
import numpy as np
def compute_eigenvalues_eigenvectors(matrix):
  eigenvalues, eigenvectors = np.linalg.eig(matrix)
  return eigenvalues,eigenvectors

matrix = np.array([[0.9, 0.2], [0.1, 0.8]])
eigenvalues, eigenvectors = compute_eigenvalues_eigenvectors(matrix)
print(eigenvectors)

# EigenValue
import numpy as np
from numpy import dot
from numpy.linalg import norm

def compute_cosine(v1, v2):
  cos_sim = computeDotProduct(v1,v2) / (computeVectorLength(v1)*computeVectorLength(v2))

  return cos_sim

x = np.array([1, 2, 3, 4])
y = np.array([1, 0, 3, 0])
result = compute_cosine(x,y)
print(round(result, 3))